// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accounts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/calendar/events/[eventId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/events/[eventId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/calendar/events/[eventId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/calendar/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/calendar/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cli/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cli/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cli/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cli/poll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cli/poll">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cli/poll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cli/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cli">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cli/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cli/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cli/state">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cli/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/thread/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/thread">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/thread/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/[id]/attachments/[attachmentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails/[id]/attachments/[attachmentId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/[id]/attachments/[attachmentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/[id]/forward/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails/[id]/forward">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/[id]/forward/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/emails/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails/send">> = Specific
  const handler = {} as typeof import("../../../src/app/api/emails/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
